import { useEffect, useMemo, useState } from "react";
import { Check, ChevronRight, FileCode2, KeyRound, Palette, Plus, Radio, RefreshCw, Shield, SlidersHorizontal, Trash2, Wifi } from "lucide-react";
import { createRoot } from "react-dom/client";
import { AppSettings, defaultSettings, LogEntry, ProviderProfile, ThemeMode } from "./types";
import { clearLogs, loadLogs } from "./storage";
import { useSettings, useTheme } from "./use-settings";
import { listModels, probeAudioEndpoints } from "./provider";
import { deleteScript, listScripts, newScript, saveScript, UserScript } from "./script-store";
import "./tokens.css";
import "./vela-options.css";

const sections = ["Geral", "Aparência", "Agente", "Navegador", "Contexto", "Voz", "Providers", "Scripts", "Permissões", "Atalhos", "Avançado"] as const;
type Section = typeof sections[number];

function Row({ label, description, children }: { label: string; description?: string; children: React.ReactNode }) { return <div className="setting-row"><div><strong>{label}</strong>{description && <small>{description}</small>}</div><div className="setting-control">{children}</div></div>; }
function Toggle({ checked, onChange }: { checked: boolean; onChange: (value: boolean) => void }) { return <button className={`toggle ${checked ? "on" : ""}`} role="switch" aria-checked={checked} onClick={() => onChange(!checked)}><span /></button>; }

function Options() {
  const { settings, update, saved } = useSettings(420);
  const [section, setSection] = useState<Section>("Aparência");
  const [models, setModels] = useState<Record<string, string[]>>({});
  const [loadingModels, setLoadingModels] = useState<string | null>(null);
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [scripts, setScripts] = useState<UserScript[]>([]);
  const [scriptStatus, setScriptStatus] = useState<string | null>(null);
  const [probe, setProbe] = useState<Record<string, string> | null>(null);
  const [probing, setProbing] = useState(false);
  useEffect(() => { void loadLogs().then(setLogs); void listScripts().then(setScripts); }, []);
  useTheme(settings);
  const updateProvider = (id: string, patch: Partial<ProviderProfile>) => update((current) => ({ providers: current.providers.map((provider) => provider.id === id ? { ...provider, ...patch } : provider) }));
  const addProvider = () => { const provider: ProviderProfile = { ...defaultSettings.providers[0], id: `provider-${Date.now()}`, name: "Novo provider", baseUrl: "", protocol: "openai-compatible", apiKey: "", defaultModel: "" }; update((current) => ({ providers: [...current.providers, provider], activeProviderId: provider.id })); };
  const refreshModels = async (provider: ProviderProfile) => { setLoadingModels(provider.id); try { const result = await listModels(provider); const ids = result.map((model) => model.id); setModels((current) => ({ ...current, [provider.id]: ids })); if (!provider.defaultModel && ids[0]) updateProvider(provider.id, { defaultModel: ids[0] }); } catch { setModels((current) => ({ ...current, [provider.id]: [] })); } finally { setLoadingModels(null); } };
  const runProbe = async (provider: ProviderProfile) => {
    setProbing(true);
    try {
      const status = await probeAudioEndpoints(provider);
      const label = (code: number) => code === 0 ? "inalcançável" : code === 404 || code === 405 ? "não existe" : code === 401 || code === 403 ? "existe (credencial)" : `existe (HTTP ${code})`;
      setProbe(Object.fromEntries(Object.entries(status).map(([path, code]) => [path, label(code)])));
      const exists = (code: number) => code !== 0 && code !== 404 && code !== 405;
      updateProvider(provider.id, { capabilities: { ...provider.capabilities, webFetch: exists(status["web/fetch"] ?? 0), audio: exists(status["audio/transcriptions"] ?? 0) } });
    } finally { setProbing(false); }
  };
  const activeProvider = useMemo(() => settings.providers.find((provider) => provider.id === settings.activeProviderId), [settings]);
  const updateScript = (id: string, patch: Partial<UserScript>) => setScripts((current) => current.map((script) => script.id === id ? { ...script, ...patch, updatedAt: Date.now() } : script));
  const runScript = async (script: UserScript) => { const tab = (await chrome.tabs.query({ active: true, lastFocusedWindow: true }))[0]; if (!tab?.id) { setScriptStatus("Nenhuma aba ativa encontrada."); return; } const result = await chrome.runtime.sendMessage({ type: "script:run", scriptId: script.id, tabId: tab.id }) as { ok?: boolean; result?: Array<{ result?: string }>; error?: string }; setScriptStatus(result.ok ? `${script.name}: ${result.result?.[0]?.result ?? "Executado."}` : result.error ?? "Falha ao executar script."); };
  const content = (() => {
    if (section === "Aparência") return <><h1>Aparência</h1><p className="section-intro">A identidade Vela permanece discreta; o sinal aparece quando o agente está presente.</p><div className="settings-group"><Row label="Tema" description="Escolha como a interface deve aparecer."><select value={settings.theme} onChange={(event) => update({ theme: event.target.value as ThemeMode })}><option value="system">Seguir sistema</option><option value="dark">Escuro</option><option value="light">Claro</option></select></Row><Row label="Nome do produto"><input value={settings.brand.appName} onChange={(event) => update({ brand: { ...settings.brand, appName: event.target.value } })} /></Row><Row label="Cor de sinal" description="Usada para foco, voz e controle do navegador."><span className="color-control"><input type="color" value={settings.brand.accentColor || "#58d8cd"} onChange={(event) => update({ brand: { ...settings.brand, accentColor: event.target.value } })} /><code>{settings.brand.accentColor || "automático"}</code>{settings.brand.accentColor && <button className="secondary-button" onClick={() => update({ brand: { ...settings.brand, accentColor: "" } })}>Restaurar</button>}</span></Row></div></>;
    if (section === "Agente") return <><h1>Agente</h1><p className="section-intro">Defina quanto controle a Vela pode exercer e quais sinais visuais deseja ver.</p><div className="settings-group"><Row label="Autonomia"><select value={settings.agent.autonomy} onChange={(event) => update({ agent: { ...settings.agent, autonomy: event.target.value as AppSettings["agent"]["autonomy"] } })}><option value="observe">Observar</option><option value="assist">Assistir</option><option value="auto">Auto</option></select></Row><Row label="Cursor da Vela" description="O cursor viaja até o alvo e a ação dispara na chegada."><Toggle checked={settings.agent.showCursor} onChange={(value) => update({ agent: { ...settings.agent, showCursor: value } })} /></Row><Row label="Velocidade do cursor" description="Instantâneo não espera o trajeto."><select value={settings.agent.cursorSpeed} onChange={(event) => update({ agent: { ...settings.agent, cursorSpeed: event.target.value as AppSettings["agent"]["cursorSpeed"] } })}><option value="natural">Natural</option><option value="fast">Rápido</option><option value="instant">Instantâneo</option></select></Row><Row label="Borda de controle"><Toggle checked={settings.agent.showControlBorder} onChange={(value) => update({ agent: { ...settings.agent, showControlBorder: value } })} /></Row><Row label="Destaque de alvo"><Toggle checked={settings.agent.showTargetHighlights} onChange={(value) => update({ agent: { ...settings.agent, showTargetHighlights: value } })} /></Row></div></>;
    if (section === "Contexto") return <><h1>Contexto</h1><p className="section-intro">Escolha o que a Vela pode usar na tarefa atual.</p><div className="settings-group"><Row label="Página atual" description="URL, título e conteúdo relevante."><Toggle checked={settings.context.currentPage} onChange={(value) => update({ context: { ...settings.context, currentPage: value } })} /></Row><Row label="Texto selecionado"><Toggle checked={settings.context.selection} onChange={(value) => update({ context: { ...settings.context, selection: value } })} /></Row><Row label="Abas da sessão"><Toggle checked={settings.context.sessionTabs} onChange={(value) => update({ context: { ...settings.context, sessionTabs: value } })} /></Row><Row label="Abas fora da sessão"><Toggle checked={settings.context.outsideTabs} onChange={(value) => update({ context: { ...settings.context, outsideTabs: value } })} /></Row></div></>;
    if (section === "Voz") return <><h1>Voz</h1><p className="section-intro">Live Voice continua no documento offscreen mesmo quando a sidebar fecha. Configure os modelos de áudio encaminhados pelo OmniRoute.</p><div className="settings-group"><Row label="Modelo de transcrição" description="Endpoint /api/v1/audio/transcriptions."><input className="mono" value={settings.voice.transcriptionModel} onChange={(event) => update({ voice: { ...settings.voice, transcriptionModel: event.target.value } })} /></Row><Row label="Modelo de fala" description="Endpoint /api/v1/audio/speech."><input className="mono" value={settings.voice.speechModel} onChange={(event) => update({ voice: { ...settings.voice, speechModel: event.target.value } })} /></Row><Row label="Voz"><input value={settings.voice.speechVoice} onChange={(event) => update({ voice: { ...settings.voice, speechVoice: event.target.value } })} /></Row><Row label="Runtime"><span className="status-badge">Offscreen ativo</span></Row></div></>;
    if (section === "Providers") return <><h1>Providers</h1><p className="section-intro">Configuração técnica da conexão. As chaves ficam no armazenamento local deste perfil.</p><div className="provider-toolbar"><span>{settings.providers.length} provider(s)</span><button className="secondary-button" onClick={addProvider}><Plus size={14} /> Adicionar</button></div>{settings.providers.map((provider) => <div className="provider-section" key={provider.id}><div className="provider-section-head"><label className="provider-radio"><input type="radio" checked={activeProvider?.id === provider.id} onChange={() => update({ activeProviderId: provider.id })} /><strong>{provider.name}</strong></label>{provider.id !== "omniroute" && <button className="icon-danger" onClick={() => update({ providers: settings.providers.filter((item) => item.id !== provider.id) })} aria-label="Remover provider"><Trash2 size={15} /></button>}</div><div className="settings-grid"><label>Nome<input value={provider.name} onChange={(event) => updateProvider(provider.id, { name: event.target.value })} /></label><label>Base URL<input className="mono" value={provider.baseUrl} onChange={(event) => updateProvider(provider.id, { baseUrl: event.target.value })} /></label><label>Protocolo<select value={provider.protocol} onChange={(event) => updateProvider(provider.id, { protocol: event.target.value as ProviderProfile["protocol"] })}><option value="omnirouter">OmniRoute</option><option value="openai-compatible">OpenAI-compatible</option><option value="custom">Custom</option></select></label><label><span><KeyRound size={12} /> Chave de API</span><input type="password" value={provider.apiKey} placeholder="não exibida" onChange={(event) => updateProvider(provider.id, { apiKey: event.target.value })} /></label><label>Modelo padrão<div className="model-inline"><input className="mono" list={`models-${provider.id}`} value={provider.defaultModel} onChange={(event) => updateProvider(provider.id, { defaultModel: event.target.value })} /><button className="secondary-button" onClick={() => void refreshModels(provider)} disabled={loadingModels === provider.id}><RefreshCw size={13} />{loadingModels === provider.id ? "..." : "Modelos"}</button></div><datalist id={`models-${provider.id}`}>{(models[provider.id] ?? []).map((model) => <option value={model} key={model} />)}</datalist>{models[provider.id]?.length ? <small>{models[provider.id].length} modelos encontrados</small> : null}</label></div><div className="settings-group"><Row label="Diagnóstico" description="Descobre quais endpoints este gateway realmente expõe. Habilita web_fetch e voz."><button className="secondary-button" onClick={() => void runProbe(provider)} disabled={probing || !provider.apiKey}>{probing ? "Sondando…" : "Sondar endpoints"}</button></Row>{probe && <div className="log-preview">{Object.entries(probe).map(([path, status]) => <div key={path}><code>{path}</code><span>{status}</span><span /></div>)}</div>}</div></div>)}</>;
    if (section === "Scripts") return <><h1>Scripts</h1><p className="section-intro">Automatizações pessoais executadas explicitamente na aba atual. A Vela não executa scripts automaticamente nesta etapa.</p><div className="provider-toolbar"><span>{scripts.length} script(s){scriptStatus ? ` · ${scriptStatus}` : ""}</span><button className="secondary-button" onClick={() => { const script = newScript(); setScripts((current) => [...current, script]); void saveScript(script); }}><Plus size={14} /> Novo script</button></div>{scripts.length === 0 && <div className="empty-scripts"><FileCode2 size={22} /><span>Nenhum script salvo ainda.</span></div>}{scripts.map((script) => <div className="script-section" key={script.id}><div className="script-head"><div><input className="script-name" value={script.name} onChange={(event) => updateScript(script.id, { name: event.target.value })} onBlur={() => { const current = scripts.find((item) => item.id === script.id); if (current) void saveScript(current); }} /><small>{script.matches.join(", ")}</small></div><div><button className="secondary-button" onClick={() => void runScript(script)} disabled={!script.enabled}>Executar</button><button className="secondary-button" onClick={() => { const current = scripts.find((item) => item.id === script.id); if (current) void saveScript(current); }}>Salvar</button><button className="icon-danger" onClick={() => void deleteScript(script.id).then(() => setScripts((current) => current.filter((item) => item.id !== script.id)))} aria-label="Excluir script"><Trash2 size={15} /></button></div></div><textarea className="script-editor" value={script.code} onChange={(event) => updateScript(script.id, { code: event.target.value })} onBlur={() => { const current = scripts.find((item) => item.id === script.id); if (current) void saveScript(current); }} spellCheck={false} /><label className="script-enabled"><input type="checkbox" checked={script.enabled} onChange={(event) => { updateScript(script.id, { enabled: event.target.checked }); void saveScript({ ...script, enabled: event.target.checked, updatedAt: Date.now() }); }} /> disponível para execução manual</label></div>)}</>;
    if (section === "Avançado") return <><h1>Avançado</h1><p className="section-intro">Diagnóstico local sem expor chaves ou conteúdo sensível.</p><div className="settings-group"><Row label="Registros locais" description={`${logs.length} eventos armazenados neste perfil.`}><button className="secondary-button" onClick={() => void clearLogs().then(() => setLogs([]))}>Limpar registros</button></Row></div><div className="log-preview">{logs.slice(-8).reverse().map((log) => <div key={log.id}><code>{new Date(log.createdAt).toLocaleTimeString()}</code><span className={`log-${log.level}`}>{log.level}</span><span>{log.event}</span></div>)}</div></>;
    return <><h1>{section}</h1><p className="section-intro">Esta área está preparada para a próxima etapa da Vela.</p><div className="settings-group"><Row label="Estado"><span className="status-badge pending">Em preparação</span></Row></div></>;
  })();
  return <main className="vela-options"><header className="options-topbar"><div className="settings-brand"><span className="vela-mini-mark"><Radio size={14} /></span><div><strong>{settings.brand.appName}</strong><small>Preferências</small></div></div><span className={`saved-indicator ${saved ? "visible" : ""}`}><Check size={14} /> Salvo</span></header><div className="settings-layout"><nav className="settings-nav" aria-label="Seções de configurações">{sections.map((item) => <button className={section === item ? "active" : ""} onClick={() => setSection(item)} key={item}><span>{item === "Aparência" ? <Palette size={15} /> : item === "Providers" ? <Wifi size={15} /> : item === "Scripts" ? <FileCode2 size={15} /> : item === "Permissões" ? <Shield size={15} /> : item === "Avançado" ? <SlidersHorizontal size={15} /> : <ChevronRight size={15} />}</span>{item}</button>)}</nav><section className="settings-main">{content}</section></div></main>;
}
createRoot(document.getElementById("root")!).render(<Options />);
